/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class covar_t implements lcm.lcm.LCMEncodable
{
    public long timestamp;
    public float var_x;
    public float var_y;
    public float a;
 
    public covar_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0xf647ec1f4f4874caL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.covar_t.class))
            return 0L;
 
        classes.add(lcmtypes.covar_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeLong(this.timestamp); 
 
        outs.writeFloat(this.var_x); 
 
        outs.writeFloat(this.var_y); 
 
        outs.writeFloat(this.a); 
 
    }
 
    public covar_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public covar_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.covar_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.covar_t o = new lcmtypes.covar_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.timestamp = ins.readLong();
 
        this.var_x = ins.readFloat();
 
        this.var_y = ins.readFloat();
 
        this.a = ins.readFloat();
 
    }
 
    public lcmtypes.covar_t copy()
    {
        lcmtypes.covar_t outobj = new lcmtypes.covar_t();
        outobj.timestamp = this.timestamp;
 
        outobj.var_x = this.var_x;
 
        outobj.var_y = this.var_y;
 
        outobj.a = this.a;
 
        return outobj;
    }
 
}

