/* LCM type definition class file
 * This file was automatically generated by lcm-gen
 * DO NOT MODIFY BY HAND!!!!
 */

package lcmtypes;
 
import java.io.*;
import java.util.*;
import lcm.lcm.*;
 
public final class pos_t implements lcm.lcm.LCMEncodable
{
    public boolean triangle_found;
    public boolean finished;
    public long timestamp;
    public float delta_x;
    public double theta;
 
    public pos_t()
    {
    }
 
    public static final long LCM_FINGERPRINT;
    public static final long LCM_FINGERPRINT_BASE = 0x9b1754f7ff8a2f1bL;
 
    static {
        LCM_FINGERPRINT = _hashRecursive(new ArrayList<Class<?>>());
    }
 
    public static long _hashRecursive(ArrayList<Class<?>> classes)
    {
        if (classes.contains(lcmtypes.pos_t.class))
            return 0L;
 
        classes.add(lcmtypes.pos_t.class);
        long hash = LCM_FINGERPRINT_BASE
            ;
        classes.remove(classes.size() - 1);
        return (hash<<1) + ((hash>>63)&1);
    }
 
    public void encode(DataOutput outs) throws IOException
    {
        outs.writeLong(LCM_FINGERPRINT);
        _encodeRecursive(outs);
    }
 
    public void _encodeRecursive(DataOutput outs) throws IOException
    {
        outs.writeByte( this.triangle_found ? 1 : 0); 
 
        outs.writeByte( this.finished ? 1 : 0); 
 
        outs.writeLong(this.timestamp); 
 
        outs.writeFloat(this.delta_x); 
 
        outs.writeDouble(this.theta); 
 
    }
 
    public pos_t(byte[] data) throws IOException
    {
        this(new LCMDataInputStream(data));
    }
 
    public pos_t(DataInput ins) throws IOException
    {
        if (ins.readLong() != LCM_FINGERPRINT)
            throw new IOException("LCM Decode error: bad fingerprint");
 
        _decodeRecursive(ins);
    }
 
    public static lcmtypes.pos_t _decodeRecursiveFactory(DataInput ins) throws IOException
    {
        lcmtypes.pos_t o = new lcmtypes.pos_t();
        o._decodeRecursive(ins);
        return o;
    }
 
    public void _decodeRecursive(DataInput ins) throws IOException
    {
        this.triangle_found = ins.readByte()!=0;
 
        this.finished = ins.readByte()!=0;
 
        this.timestamp = ins.readLong();
 
        this.delta_x = ins.readFloat();
 
        this.theta = ins.readDouble();
 
    }
 
    public lcmtypes.pos_t copy()
    {
        lcmtypes.pos_t outobj = new lcmtypes.pos_t();
        outobj.triangle_found = this.triangle_found;
 
        outobj.finished = this.finished;
 
        outobj.timestamp = this.timestamp;
 
        outobj.delta_x = this.delta_x;
 
        outobj.theta = this.theta;
 
        return outobj;
    }
 
}

